const ScreenKeys = Object.freeze({
  HOME_SCREEN: "HOME_SCREEN",
  PA_SSH_SERVER_CONFIG_SCREEN: "PA_SSH_SERVER_CONFIG_SCREEN",
  OPEN_SOURCE_LICENSES_SCREEN: "OPEN_SOURCE_LICENSES_SCREEN",
  LICENSE_DISPLAY_SCREEN: "LICENSE_DISPLAY_SCREEN"
});

export default ScreenKeys;
